# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/verilog/merge_test/merge_test.srcs/sources_1/bd/mergetest/ip/mergetest_merge_v1_0_0_0/mergetest_merge_v1_0_0_0.xci
# IP: The module: 'mergetest_merge_v1_0_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/verilog/merge_test/merge_test.srcs/sources_1/bd/mergetest/ip/mergetest_merge_v1_0_0_0/src/arrayFifo/arrayFifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arrayFifo || ORIG_REF_NAME==arrayFifo} -quiet] -quiet

# IP: c:/verilog/merge_test/merge_test.srcs/sources_1/bd/mergetest/ip/mergetest_merge_v1_0_0_0/src/mergedFifo/mergedFifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mergedFifo || ORIG_REF_NAME==mergedFifo} -quiet] -quiet

# XDC: c:/verilog/merge_test/merge_test.srcs/sources_1/bd/mergetest/ip/mergetest_merge_v1_0_0_0/src/arrayFifo/arrayFifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==arrayFifo || ORIG_REF_NAME==arrayFifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/verilog/merge_test/merge_test.srcs/sources_1/bd/mergetest/ip/mergetest_merge_v1_0_0_0/src/mergedFifo/mergedFifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mergedFifo || ORIG_REF_NAME==mergedFifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: c:/verilog/merge_test/merge_test.srcs/sources_1/bd/mergetest/ip/mergetest_merge_v1_0_0_0/mergetest_merge_v1_0_0_0.xci
# IP: The module: 'mergetest_merge_v1_0_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/verilog/merge_test/merge_test.srcs/sources_1/bd/mergetest/ip/mergetest_merge_v1_0_0_0/src/arrayFifo/arrayFifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arrayFifo || ORIG_REF_NAME==arrayFifo} -quiet] -quiet

# IP: c:/verilog/merge_test/merge_test.srcs/sources_1/bd/mergetest/ip/mergetest_merge_v1_0_0_0/src/mergedFifo/mergedFifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mergedFifo || ORIG_REF_NAME==mergedFifo} -quiet] -quiet

# XDC: c:/verilog/merge_test/merge_test.srcs/sources_1/bd/mergetest/ip/mergetest_merge_v1_0_0_0/src/arrayFifo/arrayFifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==arrayFifo || ORIG_REF_NAME==arrayFifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/verilog/merge_test/merge_test.srcs/sources_1/bd/mergetest/ip/mergetest_merge_v1_0_0_0/src/mergedFifo/mergedFifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mergedFifo || ORIG_REF_NAME==mergedFifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
