set_property PACKAGE_PIN R14 [get_ports {led[3]}]
set_property PACKAGE_PIN P14 [get_ports {led[2]}]
set_property PACKAGE_PIN N16 [get_ports {led[1]}]
set_property PACKAGE_PIN M14 [get_ports {led[0]}]
set_property PACKAGE_PIN H16 [get_ports clock]
set_property PACKAGE_PIN M20 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

create_clock -period 10.000 -name clock -waveform {0.000 5.000} [list clock [get_ports -filter { NAME =~  "*clock*" && DIRECTION == "IN" }]]
