# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mergetest/mergetest.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mergetest || ORIG_REF_NAME==mergetest} -quiet] -quiet

# IP: bd/mergetest/ip/mergetest_processing_system7_0_0/mergetest_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mergetest_processing_system7_0_0 || ORIG_REF_NAME==mergetest_processing_system7_0_0} -quiet] -quiet

# IP: bd/mergetest/ip/mergetest_merge_v1_0_0_0/mergetest_merge_v1_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mergetest_merge_v1_0_0_0 || ORIG_REF_NAME==mergetest_merge_v1_0_0_0} -quiet] -quiet

# IP: bd/mergetest/ip/mergetest_auto_pc_0/mergetest_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mergetest_auto_pc_0 || ORIG_REF_NAME==mergetest_auto_pc_0} -quiet] -quiet

# IP: bd/mergetest/ip/mergetest_ps7_0_axi_periph_0/mergetest_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mergetest_ps7_0_axi_periph_0 || ORIG_REF_NAME==mergetest_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/mergetest/ip/mergetest_rst_ps7_0_100M_0/mergetest_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mergetest_rst_ps7_0_100M_0 || ORIG_REF_NAME==mergetest_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/mergetest/mergetest_ooc.xdc
