set_property IOSTANDARD LVCMOS18 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports button0]
set_property IOSTANDARD LVCMOS18 [get_ports button1]
set_property IOSTANDARD LVCMOS18 [get_ports button2]
set_property IOSTANDARD LVCMOS18 [get_ports button3]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports mode]
set_property IOSTANDARD LVCMOS18 [get_ports rst]

create_clock -period 10.000 -name clk -waveform {0.000 5.000} clk

set_property PACKAGE_PIN H16 [get_ports clk]
set_property PACKAGE_PIN M19 [get_ports rst]
set_property PACKAGE_PIN D19 [get_ports button0]
set_property PACKAGE_PIN D20 [get_ports button1]
set_property PACKAGE_PIN L20 [get_ports button2]
set_property PACKAGE_PIN L19 [get_ports button3]
set_property PACKAGE_PIN R14 [get_ports {led[0]}]
set_property PACKAGE_PIN P14 [get_ports {led[1]}]
set_property PACKAGE_PIN N16 [get_ports {led[2]}]
set_property PACKAGE_PIN M14 [get_ports {led[3]}]
set_property PACKAGE_PIN M20 [get_ports mode]
